[workspace]
# Disable git releases for all packages by default
git_release_enable = false
# Disable git tags for all packages by default
git_tag_enable = false
# Disable changelog updates
changelog_update = false

# Options for 1 package
[[package]]
name = "vrixyz-test-package1"
# (Optional) Customize the git tag name to remove the `my_main_package` prefix.
git_tag_name = "v{{ version }}"

# Enable git tags for this package
git_tag_enable = true

# Enable git releases for this package
git_release_enable = true

# enable semver_checks for this package
semver_check = true
