[package]
name = "vrixyz-test-package2"
version = "0.1.0"
edition = "2024"
license = "Unlicense"
description = "a test package for me to experiment with crates.io"

[lib]
name = "vrixyz-test-package2"
path = "../../src/lib.rs"

[dependencies]
